# Generated by Django 4.2.3 on 2023-09-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baskets',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='baskets',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order_list_bought',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order_list_bought',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='order_list_bought',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='order_list_bought',
            name='group',
        ),
        migrations.RemoveField(
            model_name='order_list_bought',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='order_list_bought',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order_list_bought',
            name='price',
        ),
        migrations.AddField(
            model_name='goods',
            name='vendor_code',
            field=models.CharField(default='_', max_length=255, verbose_name='Артикул'),
        ),
        migrations.CreateModel(
            name='Order_list_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.order_list_bought', verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'История покупок итог',
                'verbose_name_plural': 'История покупок итог',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.IntegerField(default=0, verbose_name='Телефон')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showcase.payment', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Контакты покупателя',
                'verbose_name_plural': 'Контакты покупателя',
            },
        ),
    ]
