# Generated by Django 4.2.3 on 2023-08-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='showcase.group', verbose_name='Группа товара'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_group',
            field=models.CharField(db_index=True, default='_', max_length=255, verbose_name='Название группы'),
        ),
        migrations.CreateModel(
            name='Order_list_want_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='_', max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступность')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showcase.group', verbose_name='Группа товара')),
            ],
            options={
                'verbose_name': 'Товары, которые хочу купить',
                'verbose_name_plural': 'Товары, которые хочу купить',
                'ordering': ['time_create', 'name_product'],
            },
        ),
        migrations.CreateModel(
            name='Order_list_bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='_', max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showcase.group', verbose_name='Группа товара')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'История покупок',
                'ordering': ['time_create', 'name_product'],
            },
        ),
        migrations.CreateModel(
            name='Goods_in_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='_', max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступность')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showcase.group', verbose_name='Группа товара')),
            ],
            options={
                'verbose_name': 'Товары в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['-price', 'name_product'],
            },
        ),
    ]
