# Generated by Django 4.2.3 on 2023-08-31 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0002_alter_goods_in_basket_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods_in_basket',
            new_name='Basket',
        ),
    ]
