# Generated by Django 4.2.3 on 2023-09-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_goods_in_basket_quantity_and_more'),
        ('showcase', '0004_baskets_delete_basket'),
    ]

    operations = [
    ]
