# Generated by Django 4.2.3 on 2023-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_merge_20230901_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baskets',
            options={'ordering': ['product'], 'verbose_name': 'Товары в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AddField(
            model_name='baskets',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='Goods_in_basket',
        ),
    ]
