"""order_modify3

Revision ID: 3746cfc42d69
Revises: ded4014f1ba4
Create Date: 2024-02-15 10:40:36.183318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3746cfc42d69'
down_revision: Union[str, None] = 'ded4014f1ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_list', 'contacts', ['order_number'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_list', type_='foreignkey')
    # ### end Alembic commands ###
