"""price

Revision ID: 633a440dbaed
Revises: 3759233210bd
Create Date: 2023-11-27 06:31:47.755033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633a440dbaed'
down_revision: Union[str, None] = '3759233210bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('price', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'payment', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('goods', 'price')
    # ### end Alembic commands ###
