"""state_order2

Revision ID: 906a9f19ca22
Revises: 98c92222d738
Create Date: 2024-04-21 18:23:44.354693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '906a9f19ca22'
down_revision: Union[str, None] = '98c92222d738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_enum2')
    op.add_column('order_list', sa.Column('state_order', sa.Enum('received', 'not_received', name='state_order'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_list', 'state_order')
    op.create_table('test_enum2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state_enum', postgresql.ENUM('received', 'not_received', name='state_order'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_enum2_pkey')
    )
    # ### end Alembic commands ###
