"""init2

Revision ID: f8ec4ad6c03f
Revises: 7bffb1db7378
Create Date: 2023-10-29 21:00:56.619753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ec4ad6c03f'
down_revision: Union[str, None] = '7bffb1db7378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atom', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_atom'), 'item', ['atom'], unique=True)
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_unique_constraint(None, 'payment', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_index(op.f('ix_item_atom'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
