"""Database creation

Revision ID: d9eb3fd53690
Revises: 
Create Date: 2023-09-28 17:56:39.322998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9eb3fd53690'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('time_create_user', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('order_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_product', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('time_create', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['name_product'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('basket', 'user')
    op.add_column('contacts', sa.Column('pay', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'payment', ['pay'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'pay')
    op.add_column('basket', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('order_list')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
