# Generated by Django 5.0.1 on 2024-03-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delete_receipt_numbers_alter_receipt_list_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_list',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
