# Generated by Django 5.0.1 on 2024-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_receipt_list_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='_', max_length=255, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Номер накладной',
                'verbose_name_plural': 'Номера накладных',
                'ordering': ['time_create'],
            },
        ),
    ]
