# Generated by Django 5.0.1 on 2024-03-16 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_receipt_list_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='_', max_length=255, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Номер накладной',
                'verbose_name_plural': 'Номера накладных',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='receipt_list',
            options={'ordering': ['number', 'product'], 'verbose_name': 'Список товаров из приходных документов', 'verbose_name_plural': 'Списки товаров из приходных документов'},
        ),
        migrations.RemoveField(
            model_name='receipt_list',
            name='time_create',
        ),
        migrations.AddField(
            model_name='receipt_list',
            name='number',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Номер накладной'),
            preserve_default=False,
        ),
    ]
