# Generated by Django 5.0.1 on 2024-03-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_list',
            name='number_receipt',
            field=models.IntegerField(default=0, verbose_name='Номер накладной'),
        ),
    ]
