# Generated by Django 5.0.1 on 2024-03-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_receipt_list_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_list',
            name='state',
        ),
        migrations.AddField(
            model_name='receipt_number',
            name='state',
            field=models.BooleanField(default=False, verbose_name='состояние'),
        ),
    ]
