# Generated by Django 5.0.1 on 2024-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_receipt_list_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_list',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер накладной'),
        ),
    ]
