# Generated by Django 5.0.1 on 2024-03-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_receipt_list_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt_numbers',
        ),
        migrations.AlterModelOptions(
            name='receipt_list',
            options={'ordering': ['product'], 'verbose_name': 'Список приходных документов', 'verbose_name_plural': 'Списки приходных документов'},
        ),
    ]
