# Generated by Django 5.0.1 on 2024-03-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_receipt_list_state_receipt_number_state'),
        ('shop', '0016_rename_number_receipt_list_num'),
    ]

    operations = [
    ]
