"""update25.09.2023

Revision ID: abbb7a2c7b41
Revises: 38c62b6ab9f1
Create Date: 2023-09-25 22:22:37.596402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbb7a2c7b41'
down_revision: Union[str, None] = '38c62b6ab9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay', sa.String(), nullable=False)
    )
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('goods', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('group', sa.Column('slug', sa.String(), nullable=False))
    op.drop_column('order_list', 'buyer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_list', sa.Column('buyer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('group', 'slug')
    op.drop_column('goods', 'slug')
    op.drop_table('basket')
    op.drop_table('payment')
    op.drop_table('contacts')
    # ### end Alembic commands ###
