"""product in order_list not foreignkey

Revision ID: 57faeb6dabe5
Revises: 45c8bf55b46d
Create Date: 2024-03-29 15:53:58.682735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57faeb6dabe5'
down_revision: Union[str, None] = '45c8bf55b46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_list', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('order_list_product_id_fkey', 'order_list', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_list_product_id_fkey', 'order_list', 'goods', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('order_list', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
