"""state_order

Revision ID: 98c92222d738
Revises: f77d7428cec6
Create Date: 2024-04-21 18:22:56.779147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c92222d738'
down_revision: Union[str, None] = 'f77d7428cec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_enum2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_enum', sa.Enum('received', 'not_received', name='state_order'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_enum2')
    # ### end Alembic commands ###
