"""init3

Revision ID: b55031390228
Revises: f8ec4ad6c03f
Create Date: 2023-10-29 21:02:47.931036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55031390228'
down_revision: Union[str, None] = 'f8ec4ad6c03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_atom', table_name='item')
    op.drop_index('ix_item_id', table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('atom', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.create_index('ix_item_atom', 'item', ['atom'], unique=False)
    # ### end Alembic commands ###
