# Generated by Django 5.0.1 on 2024-01-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(db_index=True, default='_', max_length=255, verbose_name='Название группы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name_group'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_org', models.CharField(default='_', max_length=255, verbose_name='Название организации')),
                ('inn_kpp', models.CharField(default='0', max_length=255, verbose_name='ИНН-КПП')),
                ('ogrn', models.IntegerField(default=0, verbose_name='ОГРН')),
                ('working_mode', models.CharField(default='_', max_length=255, verbose_name='Режим работы')),
                ('about', models.TextField(blank=True, verbose_name='О компании')),
                ('adres', models.CharField(default='_', max_length=255, verbose_name='Адрес организации')),
                ('phone', models.IntegerField(default=0, verbose_name='Телефон')),
                ('email_name', models.CharField(default='_', max_length=255, verbose_name='Электронная почта')),
                ('telegram', models.CharField(default='_', max_length=255, verbose_name='Контакты в Telegram')),
                ('whatsApp', models.CharField(default='_', max_length=255, verbose_name='Контакты в WhatsApp')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организация',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='_', max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('vendor_code', models.CharField(default='_', max_length=255, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('stock', models.FloatField(verbose_name='Остаток')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступность')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.group', verbose_name='Группа товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['stock', 'name_product'],
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Order_list_bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(default='_', max_length=255, verbose_name='Покупатель')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('order_number', models.IntegerField(default=0, verbose_name='Количество')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'История покупок',
                'ordering': ['time_create', 'name_product'],
            },
        ),
    ]
