# Generated by Django 5.0.1 on 2024-02-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_url_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url_list',
        ),
        migrations.AlterModelOptions(
            name='order_list_bought',
            options={'ordering': ['time_create', 'product_id'], 'verbose_name': 'История покупок', 'verbose_name_plural': 'Истории покупок'},
        ),
        migrations.RenameField(
            model_name='order_list_bought',
            old_name='buyer',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='order_list_bought',
            old_name='name_product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='order_list_bought',
            name='delivery_address',
            field=models.CharField(default='_', max_length=255, verbose_name='Адрес организации'),
        ),
        migrations.AddField(
            model_name='order_list_bought',
            name='phone',
            field=models.CharField(default='_', max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order_list_bought',
            name='order_number',
            field=models.IntegerField(verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order_list_bought',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order_list_bought',
            name='time_create',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
    ]
