# Generated by Django 5.0.1 on 2024-10-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_buffer_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffer_receipt',
            name='product',
            field=models.CharField(default='_', max_length=255, verbose_name='Название товара'),
        ),
    ]
