# Generated by Django 5.0.1 on 2024-10-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_buffer_receipt_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='_', max_length=255, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=False, verbose_name='состояние')),
            ],
            options={
                'verbose_name': 'Номера инвентаризации',
                'verbose_name_plural': 'Номера инвентаризации',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='Inventory_buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='_', max_length=255, verbose_name='Название товара')),
                ('number_inventory', models.IntegerField(default=0, verbose_name='Номер инвентаризации')),
                ('quantity_old', models.FloatField(default=0, verbose_name='Количество было')),
                ('quantity_new', models.FloatField(default=0, verbose_name='Количество стало')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список буфер инвентаризаций',
                'verbose_name_plural': 'Списки буфер инвентаризаций',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Inventory_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_inventory', models.IntegerField(default=0, verbose_name='Номер инвентаризации')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.group', verbose_name='Группа товара')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_inventory', models.IntegerField(default=0, verbose_name='Номер инвентаризации')),
                ('quantity_old', models.FloatField(default=0, verbose_name='Количество было')),
                ('quantity_new', models.FloatField(default=0, verbose_name='Количество стало')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список инвентаризаций',
                'verbose_name_plural': 'Списки инвентаризаций',
                'ordering': ['product'],
            },
        ),
    ]
