# Generated by Django 5.0.1 on 2024-11-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_inventory_number_inventory_buffer_inventory_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory_group',
        ),
    ]
