# Generated by Django 5.0.1 on 2024-10-23 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_inventory_number_inventory_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='_', max_length=255, verbose_name='Название товара')),
                ('number_inventory', models.IntegerField(default=0, verbose_name='Номер инвентаризации')),
                ('quantity_old', models.FloatField(default=0, verbose_name='Количество было')),
                ('quantity_new', models.FloatField(default=0, verbose_name='Количество стало')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список буфер инвентаризаций',
                'verbose_name_plural': 'Списки буфер инвентаризаций',
                'ordering': ['product'],
            },
        ),
    ]
