# Generated by Django 5.0.1 on 2024-03-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_receipt_numbers_alter_receipt_list_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt_numbers',
            options={'ordering': ['time_create'], 'verbose_name': 'Номер накладной', 'verbose_name_plural': 'Номера накладных'},
        ),
    ]
