# Generated by Django 5.0.1 on 2024-03-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_receipt_list_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt_list',
            options={'ordering': ['number', 'product'], 'verbose_name': 'Список товаров из приходных документов', 'verbose_name_plural': 'Списки товаров из приходных документов'},
        ),
        migrations.RenameField(
            model_name='receipt_list',
            old_name='num',
            new_name='number',
        ),
    ]
