# Generated by Django 5.0.1 on 2024-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_receipt_list_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_list',
            name='number',
            field=models.IntegerField(default='2024, 3, 16, 8, 43, 41, 282828', verbose_name='Номер накладной'),
        ),
    ]
