# Generated by Django 5.0.1 on 2024-03-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_receipt_list_time_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt_list',
            old_name='number',
            new_name='num',
        ),
    ]
