"""28.09.2023

Revision ID: 1bef79c7a7b5
Revises: abbb7a2c7b41
Create Date: 2023-09-28 17:32:14.546353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bef79c7a7b5'
down_revision: Union[str, None] = 'abbb7a2c7b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('time_create_user', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('basket', 'user')
    op.alter_column('order_list', 'name_product',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    op.create_foreign_key(None, 'order_list', 'goods', ['name_product'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_list', type_='foreignkey')
    op.alter_column('order_list', 'name_product',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.add_column('basket', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
